apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busy
    image: busybox
    command: ["sh", "-c", "sleep 3d"]
    #command: ["sh", "-c", "while true; do sleep 3600; done"]
