apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    kubernetes.io/key1: value1
  annotations:
    appVersion: "2.0"
  namespace: kube-system
spec:
  containers:
  - name: c1
    image: nginx:1.14.2



