apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    kubernetes.io/app: web 
  name: pod4
spec:
  containers:
  - image: httpd
    name: pod4
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
