apiVersion: v1
kind: Pod
metadata:
  name: init-pod2
spec:
  containers:
  - name: application
    image: busybox
    command: ["sh", "-c", "sleep 3d"]
    volumeMounts:
      - name: sharedvol
        mountPath: /data
  initContainers:
  - name: download-repo
    image: alpine
    command: ["sh", "-c", "apk update; apk add git; mkdir /app/app-content; git clone https://github.com/mariano-italiano/lx-k_Oct.git /app/app-content"]
    volumeMounts:
      - name: sharedvol
        mountPath: /app
  volumes:
  - name: sharedvol
    emptyDir: {}
